package team6.project; 
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Vanessa
 */
public class AddCourse extends javax.swing.JPanel {

 /**
  * Creates new form AddCourse
  */
 public AddCourse() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed"
 // desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jPanel7 = new javax.swing.JPanel();
  courseTermLabel = new javax.swing.JLabel();
  courseCombo = new javax.swing.JComboBox();
  courseTitle = new javax.swing.JTextField();
  courseCode = new javax.swing.JTextField();
  courseCodeLabel = new javax.swing.JLabel();
  courseTitleLabel = new javax.swing.JLabel();
  addCourseButton = new javax.swing.JButton();

  jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

  courseTermLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  courseTermLabel.setText("Course Term:");

  courseCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] {
    "Spring 2013", "Winter 2014", "Summer 2014", "Spring 2014" }));

  courseCodeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  courseCodeLabel.setText("Course Code:");

  courseTitleLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  courseTitleLabel.setText("Course Title: ");

  addCourseButton.setText("Add");
  addCourseButton.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    addCourseButtonActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(
    jPanel7);
  jPanel7.setLayout(jPanel7Layout);
  jPanel7Layout
    .setHorizontalGroup(jPanel7Layout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        jPanel7Layout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            jPanel7Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(
                courseTermLabel)
              .addComponent(
                courseCodeLabel)
              .addComponent(
                courseTitleLabel))
          .addGap(18, 18, 18)
          .addGroup(
            jPanel7Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(
                courseTitle)
              .addComponent(
                courseCode)
              .addComponent(
                courseCombo, 0,
                259,
                Short.MAX_VALUE))
          .addGap(12, 12, 12))
      .addGroup(
        javax.swing.GroupLayout.Alignment.TRAILING,
        jPanel7Layout
          .createSequentialGroup()
          .addContainerGap(
            javax.swing.GroupLayout.DEFAULT_SIZE,
            Short.MAX_VALUE)
          .addComponent(addCourseButton)
          .addContainerGap()));
  jPanel7Layout
    .setVerticalGroup(jPanel7Layout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        jPanel7Layout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            jPanel7Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                courseCodeLabel)
              .addComponent(
                courseCode,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                20,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(
            jPanel7Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                courseTitleLabel)
              .addComponent(
                courseTitle,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(19, 19, 19)
          .addGroup(
            jPanel7Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                courseTermLabel)
              .addComponent(
                courseCombo,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(
            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
            132, Short.MAX_VALUE)
          .addComponent(addCourseButton)
          .addContainerGap()));

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
  this.setLayout(layout);
  layout.setHorizontalGroup(layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING).addGroup(
    layout.createSequentialGroup()
      .addContainerGap()
      .addComponent(jPanel7,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        Short.MAX_VALUE).addContainerGap()));
  layout.setVerticalGroup(layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING).addGroup(
    layout.createSequentialGroup()
      .addContainerGap()
      .addComponent(jPanel7,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        Short.MAX_VALUE).addContainerGap()));
 }// </editor-fold>//GEN-END:initComponents

 /**
  * Find appropriate information from fields and call the updateAddCourse
  * method
  * 
  * @param evt
  */
 private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addCourseButtonActionPerformed
  String[] s = new String[] { "Spring 2013", "Winter 2014",
    "Summer 2014", "Spring 2014" };
  String term = s[courseCombo.getSelectedIndex()];
  GradeBookUI.updateAddCourse(courseTitle.getText(),
    courseCode.getText(), term);
 }// GEN-LAST:event_addCourseButtonActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton addCourseButton;
 private javax.swing.JTextField courseCode;
 private javax.swing.JLabel courseCodeLabel;
 private javax.swing.JComboBox courseCombo;
 private javax.swing.JLabel courseTermLabel;
 private javax.swing.JTextField courseTitle;
 private javax.swing.JLabel courseTitleLabel;
 private javax.swing.JPanel jPanel7;
 // End of variables declaration//GEN-END:variables
}
