package team6.project;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Vanessa
 */
public class AddStudent extends javax.swing.JPanel {

 /**
  * Creates new form AddStudent
  */
 public AddStudent() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed"
 // desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  jPanel11 = new javax.swing.JPanel();
  lastName = new javax.swing.JTextField();
  firstName = new javax.swing.JTextField();
  firstNameLabel = new javax.swing.JLabel();
  lastNameLabel = new javax.swing.JLabel();
  addStudentButton = new javax.swing.JButton();
  studentIDLabel = new javax.swing.JLabel();
  studentID = new javax.swing.JTextField();
  studentEmailLabel = new javax.swing.JLabel();
  studentEmail = new javax.swing.JTextField();

  jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

  firstNameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  firstNameLabel.setText("First Name:");

  lastNameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  lastNameLabel.setText("Last Name:");

  addStudentButton.setText("Add");
  addStudentButton.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    addStudentButtonActionPerformed(evt);
   }
  });

  studentIDLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  studentIDLabel.setText("Student ID:");

  studentEmailLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  studentEmailLabel.setText("Email:");

  javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(
    jPanel11);
  jPanel11.setLayout(jPanel11Layout);
  jPanel11Layout
    .setHorizontalGroup(jPanel11Layout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        jPanel11Layout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            jPanel11Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(
                jPanel11Layout
                  .createSequentialGroup()
                  .addGroup(
                    jPanel11Layout
                      .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(
                        jPanel11Layout
                          .createSequentialGroup()
                          .addGap(0,
                            0,
                            Short.MAX_VALUE)
                          .addComponent(
                            addStudentButton))
                      .addGroup(
                        jPanel11Layout
                          .createSequentialGroup()
                          .addComponent(
                            studentEmailLabel)
                          .addGap(59,
                            59,
                            59)
                          .addComponent(
                            studentEmail)))
                  .addContainerGap())
              .addGroup(
                jPanel11Layout
                  .createSequentialGroup()
                  .addGroup(
                    jPanel11Layout
                      .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(
                        firstNameLabel)
                      .addComponent(
                        lastNameLabel)
                      .addComponent(
                        studentIDLabel))
                  .addGap(30,
                    30,
                    30)
                  .addGroup(
                    jPanel11Layout
                      .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(
                        jPanel11Layout
                          .createSequentialGroup()
                          .addComponent(
                            studentID)
                          .addContainerGap())
                      .addGroup(
                        jPanel11Layout
                          .createSequentialGroup()
                          .addGroup(
                            jPanel11Layout
                              .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(
                                lastName,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                260,
                                Short.MAX_VALUE)
                              .addComponent(
                                firstName))
                          .addGap(12,
                            12,
                            12)))))));
  jPanel11Layout
    .setVerticalGroup(jPanel11Layout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        jPanel11Layout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            jPanel11Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                firstNameLabel)
              .addComponent(
                firstName,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                20,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(
            jPanel11Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                lastNameLabel)
              .addComponent(
                lastName,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(
            jPanel11Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                studentIDLabel)
              .addComponent(
                studentID,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(
            jPanel11Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                studentEmailLabel)
              .addComponent(
                studentEmail,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(
            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
            javax.swing.GroupLayout.DEFAULT_SIZE,
            Short.MAX_VALUE)
          .addComponent(addStudentButton)
          .addContainerGap()));

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
  this.setLayout(layout);
  layout.setHorizontalGroup(layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING).addGroup(
    layout.createSequentialGroup()
      .addContainerGap()
      .addComponent(jPanel11,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        Short.MAX_VALUE).addContainerGap()));
  layout.setVerticalGroup(layout.createParallelGroup(
    javax.swing.GroupLayout.Alignment.LEADING).addGroup(
    layout.createSequentialGroup()
      .addContainerGap()
      .addComponent(jPanel11,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        javax.swing.GroupLayout.DEFAULT_SIZE,
        Short.MAX_VALUE).addContainerGap()));
 }// </editor-fold>//GEN-END:initComponents

 private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addStudentButtonActionPerformed
  // TODO add your handling code here:
 }// GEN-LAST:event_addStudentButtonActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton addStudentButton;
 private javax.swing.JTextField firstName;
 private javax.swing.JLabel firstNameLabel;
 private javax.swing.JPanel jPanel11;
 private javax.swing.JTextField lastName;
 private javax.swing.JLabel lastNameLabel;
 private javax.swing.JTextField studentEmail;
 private javax.swing.JLabel studentEmailLabel;
 private javax.swing.JTextField studentID;
 private javax.swing.JLabel studentIDLabel;
 // End of variables declaration//GEN-END:variables
}
