package team6.project;
import java.util.ArrayList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Vanessa
 */
public class DeleteCourse extends javax.swing.JPanel {

 private ArrayList<Course> courses;

 /**
  * Creates new form DeleteCourse
  */
 public DeleteCourse(ArrayList<Course> courses) {
  this.courses = courses;
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed"
 // desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  selectCourseLabel = new javax.swing.JLabel();
  selectCourse = new javax.swing.JComboBox();
  jPanel10 = new javax.swing.JPanel();
  courseCodeLabel = new javax.swing.JLabel();
  courseTitleLabel = new javax.swing.JLabel();
  courseTermLabel = new javax.swing.JLabel();
  courseCode = new javax.swing.JLabel();
  courseTitle = new javax.swing.JLabel();
  courseTerm = new javax.swing.JLabel();
  deleteCourseButton = new javax.swing.JButton();

  selectCourseLabel.setText("Select Course:");

  selectCourse.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    selectCourseActionPerformed(evt);
   }
  });

  // Add list of courses to combo box
  for (int i = 0; i < courses.size(); i++)
   selectCourse.addItem(courses.get(i));

  jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

  courseCodeLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  courseCodeLabel.setText("Course Code:");

  courseTitleLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  courseTitleLabel.setText("Course Title:");

  courseTermLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  courseTermLabel.setText("Course Term:");

  courseCode.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

  courseTitle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

  courseTerm.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

  deleteCourseButton.setText("Delete");
  deleteCourseButton
    .addActionListener(new java.awt.event.ActionListener() {
     public void actionPerformed(java.awt.event.ActionEvent evt) {
      deleteCourseButtonActionPerformed(evt);
     }
    });

  javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(
    jPanel10);
  jPanel10.setLayout(jPanel10Layout);
  jPanel10Layout
    .setHorizontalGroup(jPanel10Layout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        javax.swing.GroupLayout.Alignment.TRAILING,
        jPanel10Layout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            jPanel10Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(
                jPanel10Layout
                  .createSequentialGroup()
                  .addGap(0,
                    0,
                    Short.MAX_VALUE)
                  .addComponent(
                    deleteCourseButton))
              .addGroup(
                jPanel10Layout
                  .createSequentialGroup()
                  .addGroup(
                    jPanel10Layout
                      .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(
                        courseCodeLabel)
                      .addComponent(
                        courseTitleLabel)
                      .addComponent(
                        courseTermLabel))
                  .addGap(18,
                    18,
                    18)
                  .addGroup(
                    jPanel10Layout
                      .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(
                        courseCode,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        261,
                        Short.MAX_VALUE)
                      .addComponent(
                        courseTitle,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE)
                      .addComponent(
                        courseTerm,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        javax.swing.GroupLayout.DEFAULT_SIZE,
                        Short.MAX_VALUE))))
          .addContainerGap()));
  jPanel10Layout
    .setVerticalGroup(jPanel10Layout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        jPanel10Layout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            jPanel10Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                courseCodeLabel)
              .addComponent(
                courseCode))
          .addGap(18, 18, 18)
          .addGroup(
            jPanel10Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                courseTitleLabel)
              .addComponent(
                courseTitle))
          .addGap(18, 18, 18)
          .addGroup(
            jPanel10Layout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                courseTermLabel)
              .addComponent(
                courseTerm))
          .addPreferredGap(
            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
            122, Short.MAX_VALUE)
          .addComponent(deleteCourseButton)
          .addContainerGap()));

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
  this.setLayout(layout);
  layout.setHorizontalGroup(layout
    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(
      layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(
          layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
              jPanel10,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE)
            .addGroup(
              layout.createSequentialGroup()
                .addComponent(
                  selectCourseLabel)
                .addGap(18, 18,
                  18)
                .addComponent(
                  selectCourse,
                  0,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE)))
        .addContainerGap()));
  layout.setVerticalGroup(layout
    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(
      layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(
          layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(selectCourseLabel)
            .addComponent(
              selectCourse,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(
          javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel10,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE).addContainerGap()));
 }// </editor-fold>//GEN-END:initComponents

 private void selectCourseActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectCourseActionPerformed
  courseCode.setText(courses.get(selectCourse.getSelectedIndex())
    .getCourseCode());
  courseTerm.setText(courses.get(selectCourse.getSelectedIndex())
    .getCourseTerm());
  courseTitle.setText(courses.get(selectCourse.getSelectedIndex())
    .getCourseTitle());
 }// GEN-LAST:event_selectCourseActionPerformed

 private void deleteCourseButtonActionPerformed(
   java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addCourseButtonActionPerformed
  if (selectCourse.getSelectedIndex() >= 0) {
   int ind = selectCourse.getSelectedIndex();
   selectCourse.remove(ind);
   GradeBookUI.updateDeleteCourse(ind);
  }
 }// GEN-LAST:event_addCourseButtonActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JLabel courseCode;
 private javax.swing.JLabel courseCodeLabel;
 private javax.swing.JLabel courseTerm;
 private javax.swing.JLabel courseTermLabel;
 private javax.swing.JLabel courseTitle;
 private javax.swing.JLabel courseTitleLabel;
 private javax.swing.JButton deleteCourseButton;
 private javax.swing.JPanel jPanel10;
 private javax.swing.JComboBox selectCourse;
 private javax.swing.JLabel selectCourseLabel;
 // End of variables declaration//GEN-END:variables
}
