package team6.project;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * 
 * @author Vanessa
 */
public class EditStudent extends javax.swing.JPanel {

 /**
  * Creates new form EditStudent
  */
 public EditStudent() {
  initComponents();
 }

 /**
  * This method is called from within the constructor to initialize the form.
  * WARNING: Do NOT modify this code. The content of this method is always
  * regenerated by the Form Editor.
  */
 @SuppressWarnings("unchecked")
 // <editor-fold defaultstate="collapsed"
 // desc="Generated Code">//GEN-BEGIN:initComponents
 private void initComponents() {

  editStudentPane = new javax.swing.JPanel();
  editStudentButton = new javax.swing.JButton();
  firstName = new javax.swing.JTextField();
  lastName = new javax.swing.JTextField();
  studentID = new javax.swing.JTextField();
  studentEmail = new javax.swing.JTextField();
  firstNameLabel = new javax.swing.JLabel();
  lastNameLabel = new javax.swing.JLabel();
  studentIDLabel = new javax.swing.JLabel();
  studentEmailLabel = new javax.swing.JLabel();
  selectCourse1 = new javax.swing.JComboBox();
  selectCourseLabel = new javax.swing.JLabel();
  selectStudentLabel = new javax.swing.JLabel();
  studentListCombo = new javax.swing.JComboBox();

  editStudentPane.setBorder(javax.swing.BorderFactory
    .createEtchedBorder());

  editStudentButton.setText("Edit");
  editStudentButton
    .addActionListener(new java.awt.event.ActionListener() {
     public void actionPerformed(java.awt.event.ActionEvent evt) {
      editStudentButtonActionPerformed(evt);
     }
    });

  firstNameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  firstNameLabel.setText("First Name:");

  lastNameLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  lastNameLabel.setText("Last Name:");

  studentIDLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  studentIDLabel.setText("Student ID:");

  studentEmailLabel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
  studentEmailLabel.setText("Email:");

  javax.swing.GroupLayout editStudentPaneLayout = new javax.swing.GroupLayout(
    editStudentPane);
  editStudentPane.setLayout(editStudentPaneLayout);
  editStudentPaneLayout
    .setHorizontalGroup(editStudentPaneLayout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        editStudentPaneLayout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            editStudentPaneLayout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                editStudentPaneLayout
                  .createSequentialGroup()
                  .addGap(0,
                    305,
                    Short.MAX_VALUE)
                  .addComponent(
                    editStudentButton))
              .addGroup(
                editStudentPaneLayout
                  .createSequentialGroup()
                  .addComponent(
                    studentEmailLabel)
                  .addGap(59,
                    59,
                    59)
                  .addComponent(
                    studentEmail))
              .addGroup(
                editStudentPaneLayout
                  .createSequentialGroup()
                  .addGroup(
                    editStudentPaneLayout
                      .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(
                        firstNameLabel)
                      .addComponent(
                        lastNameLabel)
                      .addComponent(
                        studentIDLabel))
                  .addGap(30,
                    30,
                    30)
                  .addGroup(
                    editStudentPaneLayout
                      .createParallelGroup(
                        javax.swing.GroupLayout.Alignment.LEADING)
                      .addComponent(
                        studentID)
                      .addGroup(
                        editStudentPaneLayout
                          .createSequentialGroup()
                          .addGroup(
                            editStudentPaneLayout
                              .createParallelGroup(
                                javax.swing.GroupLayout.Alignment.TRAILING)
                              .addComponent(
                                lastName,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                260,
                                Short.MAX_VALUE)
                              .addComponent(
                                firstName))
                          .addGap(2,
                            2,
                            2)))))
          .addContainerGap()));
  editStudentPaneLayout
    .setVerticalGroup(editStudentPaneLayout
      .createParallelGroup(
        javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(
        editStudentPaneLayout
          .createSequentialGroup()
          .addContainerGap()
          .addGroup(
            editStudentPaneLayout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                firstNameLabel)
              .addComponent(
                firstName,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                20,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(
            editStudentPaneLayout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                lastNameLabel)
              .addComponent(
                lastName,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(
            editStudentPaneLayout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                studentIDLabel)
              .addComponent(
                studentID,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGap(18, 18, 18)
          .addGroup(
            editStudentPaneLayout
              .createParallelGroup(
                javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(
                studentEmailLabel)
              .addComponent(
                studentEmail,
                javax.swing.GroupLayout.PREFERRED_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.PREFERRED_SIZE))
          .addPreferredGap(
            javax.swing.LayoutStyle.ComponentPlacement.RELATED,
            49, Short.MAX_VALUE)
          .addComponent(editStudentButton)
          .addContainerGap()));

  selectCourse1.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    selectCourse1ActionPerformed(evt);
   }
  });

  selectCourseLabel.setText("Select Course:");

  selectStudentLabel.setText("Select Student:");

  studentListCombo.addActionListener(new java.awt.event.ActionListener() {
   public void actionPerformed(java.awt.event.ActionEvent evt) {
    studentListComboActionPerformed(evt);
   }
  });

  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
  this.setLayout(layout);
  layout.setHorizontalGroup(layout
    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(
      layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(
          layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
              editStudentPane,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE)
            .addGroup(
              layout.createSequentialGroup()
                .addGroup(
                  layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(
                      selectStudentLabel)
                    .addComponent(
                      selectCourseLabel))
                .addGap(18, 18,
                  18)
                .addGroup(
                  layout.createParallelGroup(
                    javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(
                      selectCourse1,
                      0,
                      javax.swing.GroupLayout.DEFAULT_SIZE,
                      Short.MAX_VALUE)
                    .addComponent(
                      studentListCombo,
                      0,
                      288,
                      Short.MAX_VALUE))))
        .addContainerGap()));
  layout.setVerticalGroup(layout
    .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
    .addGroup(
      layout.createSequentialGroup()
        .addContainerGap(
          javax.swing.GroupLayout.DEFAULT_SIZE,
          Short.MAX_VALUE)
        .addGroup(
          layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(selectCourseLabel)
            .addComponent(
              selectCourse1,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(
          javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(
          layout.createParallelGroup(
            javax.swing.GroupLayout.Alignment.BASELINE)
            .addComponent(
              selectStudentLabel)
            .addComponent(
              studentListCombo,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(
          javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(editStudentPane,
          javax.swing.GroupLayout.PREFERRED_SIZE,
          javax.swing.GroupLayout.DEFAULT_SIZE,
          javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap()));
 }// </editor-fold>//GEN-END:initComponents

 private void editStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editStudentButtonActionPerformed
  // TODO add your handling code here:
 }// GEN-LAST:event_editStudentButtonActionPerformed

 private void selectCourse1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_selectCourse1ActionPerformed
  // TODO add your handling code here:
 }// GEN-LAST:event_selectCourse1ActionPerformed

 private void studentListComboActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_studentListComboActionPerformed
  // TODO add your handling code here:
 }// GEN-LAST:event_studentListComboActionPerformed

 // Variables declaration - do not modify//GEN-BEGIN:variables
 private javax.swing.JButton editStudentButton;
 private javax.swing.JPanel editStudentPane;
 private javax.swing.JTextField firstName;
 private javax.swing.JLabel firstNameLabel;
 private javax.swing.JTextField lastName;
 private javax.swing.JLabel lastNameLabel;
 private javax.swing.JComboBox selectCourse;
 private javax.swing.JComboBox selectCourse1;
 private javax.swing.JLabel selectCourseLabel;
 private javax.swing.JLabel selectStudentLabel;
 private javax.swing.JTextField studentEmail;
 private javax.swing.JLabel studentEmailLabel;
 private javax.swing.JTextField studentID;
 private javax.swing.JLabel studentIDLabel;
 private javax.swing.JComboBox studentListCombo;
 // End of variables declaration//GEN-END:variables
}
